### ISSUE TITLE
[BUG] Crash when trying to write starscript expression

### ISSUE THREAD

**Issue by ghost** [RacoonDog/Tokyo-Client#3]
When trying to start Meteor StarScript™ expression by typing "{" the game crashes, it behaves differently without Tokyo client,
additionally [Not enough crashes mod](https://github.com/natanfudge/not-enough-crashes) says, that it's caused by Tokyo client
[crash report](https://gist.github.com/ce593adfd3075a496229322f5adcfdec)

**Comment by crosby-moe** [comment]
btw don't use electron, it's dead
