### ISSUE TITLE
Add compatibility with 1.20.1 and show the jar file for it. Thanks alot!

### ISSUE THREAD

**Issue by Python9874** [RacoonDog/Tokyo-Client#6]
Everyone wants meteor client addons to support 1.20.1. Would you mind updating it to 1.20.1 the jar file so if i'm on Meteor version 1.20.1 it is compatible with fabric. Thanks alot: Seb!

**Comment by crosby-moe** [comment]
Sure yeah I can do that tomorrow probably

**Comment by crosby-moe** [comment]
wow i did that quickly 👍
