### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by Indejann** [RacoonDog/Tokyo-Client#7]
its a rat

**Comment by airplane** [comment]
so true

**Comment by crosby-moe** [comment]
> its a rat

its true, its a rat 😔

**Comment by Wide-Cat** [comment]
🐀

**Comment by Big-Iron-Cheems** [comment]
Biggest rat I've ever seen.
It clearly outranks even the foulest Parisian beasts.
![](https://github.com/RacoonDog/Tokyo-Client/assets/52252627/a02dbf59-780f-4d40-b89d-c9b0d8084ec9)

**Comment by machiecodes** [comment]
new yrok client (rats)

**Comment by Paneled** [comment]
Mega rat. Crosby also known as crystallinqq this account has been crosbyd by crosby

**Comment by RegalAether** [comment]
this account has been token logged by crosby. 顶部的per download tokyo-client是安全的 emp搞砸

**Comment by CrytoPal** [comment]
I got hacked by this, don't run it
